version: "3.7"
services:
  nginx:
    image: 'nginx:1.19.3'
    depends_on:
    - 'vault'
    ports:
    - '80:80'
    volumes:
    - './etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
  vault:
    image: 'vault:1.6.3'
    container_name: 'vault'
    restart: 'always'
    depends_on:
    - 'postgresql'
    cap_add:
    - 'IPC_LOCK'
    expose:
    - '8200'
    command: ['server', '--config', '/vault/config.json']
    volumes:
    - 'certs:/certs'
    - './vault/config.json:/vault/config.json'
    - 'logs:/vault/logs'
  postgresql:
    image: 'postgres:13.2'
    restart: 'always'
    environment:
    - 'POSTGRES_DB=vault'
    - 'POSTGRES_USER=vault'
    - 'POSTGRES_PASSWORD=vault'
    expose:
    - '5432'
    volumes:
    - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    - 'postgresql:/var/lib/postgresql/data'
  openssh:
    image: 'openssh-server'
    restart: 'always'
    volumes:
    - 'openssh:/etc/ssh'
    - 'certs:/certs:ro'
    - 'git:/srv/git'
    - './etc/ssh/sshd_config:/etc/ssh/sshd_config:ro'
    - './etc/ssh/ssh_config:/etc/ssh/ssh_config:ro'
    - './etc/pam.d/sshd:/etc/pam.d/sshd'
    - './opt/pam-exec-oauth2/pam-exec-oauth2.yaml:/opt/pam-exec-oauth2/pam-exec-oauth2.yaml'
    - './usr/share/libpam-script/pam_script_auth:/usr/share/libpam-script/pam_script_auth'
    # - './etc/pam.d/common-session:/etc/pam.d/common-session'
    # - './etc/pam.d/common-auth:/etc/pam.d/common-auth'
    # - './usr/share/pam-configs/mkhomedir:/usr/share/pam-configs/mkhomedir'
    # - './opt/pam-keycloak-oidc/pam-keycloak-oidc.tml:/opt/pam-keycloak-oidc/pam-keycloak-oidc.tml'
    # - './usr/share/libpam-script/pam_script_auth:/usr/share/libpam-script/pam_script_auth'
    # - 'rsyslog:/var/run'
    cap_add:
    - 'SYS_CHROOT'
    - 'SETGID'
    - 'SETUID'
    - 'CHOWN'
    ports:
    - '22:22'
volumes:
  logs:
  postgresql:
  certs:
  openssh:
  git:
  # rsyslog:
  #   external: true
